### ISSUE TITLE
Fighter qualification

### ISSUE THREAD

**Issue by seawayne** [novumvita/SwashbucklerWOTR#1]
Fighter level equivalency does not appear to work.

**Comment by novumvita** [comment]
reuploaded 1.0.2 with fix, please try it out and confirm it works

**Comment by seawayne** [comment]
Still getting a Fighter level 0 at level 4 when looking at prereqs for Weapon Specialization.

**Comment by novumvita** [comment]
sorry, i uploaded the wrong file. reuploaded again.

**Comment by seawayne** [comment]
Yep, works good!
