### ISSUE TITLE
Rostland Bravo doesn't apply Swashbuckler Finesse to Dueling sword.

### ISSUE THREAD

**Issue by Nauleon2** [novumvita/SwashbucklerWOTR#18]
I mean, no Swashbuckler apply the Finesse to that weapon, but it seems that the bravo should. If you pick weapon finesse mythic the damage roll change to dex, but the str atack roll is still there.

**Comment by novumvita** [comment]
you are wielding it one handed right?

**Comment by Nauleon2** [comment]
I have tried both one and two-handed. The other weapons apply dex even when two-handed, i didn't know that should not work. 

Ty for the mod, it's an amazing class and it's very different from other classes

**Comment by novumvita** [comment]
rostland bravo has the same swashbuckler finesse as other archetypes. all it gains is dueling sword proficiency. so, you'll need to take aldori dueling mastery to treat it as a swashbuckler weapon.
kinda silly, honestly, but thats what the rules say unless im misreading it.

**Comment by Nauleon2** [comment]
I made the testing and you are right:

- The finnesse works with dueling if you pick "aldori dueling mastery". For all the other archetypes it doesn't seems to be bad, but for the bravo it is weird and deeply underwelhming, I have seen that it was an error the writters of the tabletop had. I truly recommend to add the aldori feat in level 1 or to completly remove the piercing finesse for the Bravo and remake the archetype. A tax-feat that is mandatory if you want to use some of the deeds made the Bravo very confusing (i need to be a regular swas until level 3, and then... do i change my combat technique?)
In that particular case i truly recommend to take distance from TT and make the change, as WOTR is more min-max and class-optimized than a regular pathfinder campaing 

- The finesse works with dervish dance and slashing grace. That makes the class more fun, as you can be a agile fighter even with axes, jaja.

- In both cases the finesse still work if i double-handle the weapon. I would not change that, if you do the damage the class is going to do fall against every other competent melee fighter in the game and you doesn't get enough in return to be worth

Ty for the time to answer me and for the work to adapt the class to the game

**Comment by novumvita** [comment]
i agree. i will make the change if/when i get back to modding, which might be when the dlc drops. will keep the issue open so i dont forget.
and thank you for your kind words, glad you enjoyed swashbuckling.

**Comment by novumvita** [comment]
rostland bravo now gets aldori dueling mastery as a bonus feat
