### ISSUE TITLE
Weapon Training qualifying

### ISSUE THREAD

**Issue by seawayne** [novumvita/SwashbucklerWOTR#2]
I'm not sure if it would be more trouble than it's worth or not to make it work, but at present, the weapon training for swashbucklers doesn't meet whatever parameter that things like Gloves of Duelling are looking for to increase its value.

**Comment by novumvita** [comment]
gloves of dueling do work on the latest version on my end. ive reuploaded 1.0.2 multiple times. pls try redownloading it again and checking, if there is anything other than gloves of dueling that looks for weapon training which doesnt work, let me know

**Comment by seawayne** [comment]
Ah, I see it stacking now, though for some reason my test character (Using Inevitable Excess to test it) only has a +3 bonus from it at level 20 when it should be +4?  I had lesser gloves of dueling on so I just saw the 4 and assumed it wasn't adding, rather than adding to a lower value.

**Comment by novumvita** [comment]
yeah, weapon training had issues. i think ive fixed it in the latest release, pls try it out and confirm

**Comment by seawayne** [comment]
Seems to be good.
