### ISSUE TITLE
Dodging Panache Bug

### ISSUE THREAD

**Issue by YLMstring** [novumvita/SwashbucklerWOTR#20]
Not tested but I made the same mistake once lol
willSpend should be wrapped into a component data, or it will apply to all iinstances of the component
eg. one character trigger Dodging Panache, then his willSpend will affect another person's Dodging Panache

**Comment by YLMstring** [comment]
Also it should be RuleAttackRoll, not RuleAttackWithWeapon?

**Comment by novumvita** [comment]
should be fine since willSpend is set back to false right after the triggering event right?

**Comment by novumvita** [comment]
and RuleAttackWithWeapon was because i only wanted it to work against weapon attacks, i think

**Comment by YLMstring** [comment]
Yeah on second thought, it should be fine (only buggy in purely theoretical cases that won't ever materialize)
Thanks so much for your mod!
