### ISSUE TITLE
Inspired Panache bug

### ISSUE THREAD

**Issue by YLMstring** [novumvita/SwashbucklerWOTR#21]
It says:
Each day, an inspired blade gains a number of panache points equal to her [Charisma](https://www.d20pfsrd.com/basics-ability-scores/ability-scores#TOC-Charisma-Cha-) modifier (minimum 1) plus her [Intelligence](https://www.d20pfsrd.com/basics-ability-scores/ability-scores#TOC-Intelligence-Int-) modifier (minimum 1), instead of just her [Charisma](https://www.d20pfsrd.com/basics-ability-scores/ability-scores#TOC-Charisma-Cha-) modifier.
Therefore, an an inspired blade with 6 cha and 16 int should end up with 4 panache. However, she only has 1 panache rn
This is because BlueprintAbilityResource.GetMaxAmount() reads this.m_Min after everything else
Thankee!

**Comment by novumvita** [comment]
fixed in 1.1.6, hopefully
