### ISSUE TITLE
issues (maybe?) for azatariel

### ISSUE THREAD

**Issue by nixgnot** [novumvita/SwashbucklerWOTR#6]
1. i cant really get the Affection of Elysium active ability
![1](https://github.com/novumvita/SwashbucklerWOTR/assets/20860979/9f22603d-e8be-4786-b0bb-c62b6be2226a)
![2](https://github.com/novumvita/SwashbucklerWOTR/assets/20860979/0d3ed81c-96e9-4692-8713-937e3ab9953c)

2. Whimsical Riposte wont really give Charisma modifier to attack & damage of riposting as it said. it only affect the parry (and so no damage bonus here)
![3](https://github.com/novumvita/SwashbucklerWOTR/assets/20860979/3f313e0f-55be-4635-8692-592d95629b68)
![4](https://github.com/novumvita/SwashbucklerWOTR/assets/20860979/3fed7258-d17a-49a3-a271-d7d7c87b34fc)
![5](https://github.com/novumvita/SwashbucklerWOTR/assets/20860979/d7d4956f-673b-4a71-9634-af1866b53c77)
![6](https://github.com/novumvita/SwashbucklerWOTR/assets/20860979/0455277f-dc2a-440b-b7a6-e222b62f9448)

**Comment by novumvita** [comment]
should be fixed in 1.0.7
